name: Deploy Dual Sites
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site:
          - name: "琳.tw"
            display_name: "琳.tw"
            worker_name: "blog"
          - name: "聆.tw"
            display_name: "聆.tw"
            worker_name: "ai-talks"

    name: Deploy ${{ matrix.site.display_name }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: jim60105/blog
          ref: master
          submodules: true
          # Workaround for issue "Persisting credentials for submodules" step failed with "Error: ENOENT: no such file or directory" when the submodule name contains non-ASCII characters
          # https://github.com/actions/checkout/issues/1959
          persist-credentials: false

      - name: Checkout `content` submodule to master
        run: |
          git -C "琳.tw/content" checkout origin/master && \
          git -C "聆.tw/content" checkout origin/master

      - name: Download and Install Zola
        run: |
          # Download zola binary from GitHub releases
          wget -O zola.tar.gz "https://github.com/getzola/zola/releases/download/v${{ vars.ZOLA_VERSION }}/zola-v${{ vars.ZOLA_VERSION }}-x86_64-unknown-linux-musl.tar.gz"

          # Extract the tar.gz
          tar -xzf zola.tar.gz

          # Move zola to /usr/local/bin and make it executable
          sudo mv zola /usr/local/bin/
          sudo chmod +x /usr/local/bin/zola

          # Verify installation
          zola --version

      - name: Switch to ${{ matrix.site.name }} site
        run: |
          chmod +x ./switch-site.sh
          ./switch-site.sh "${{ matrix.site.name }}"

      - name: Build ${{ matrix.site.name }} site
        run: zola build

      - name: Deploy ${{ matrix.site.name }} to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "latest"
